# Rmarkdown 论文写作 {#sec-rmarkdown}

Rmarkdown是markdown的一种延伸版本。
Markdown是一种流行且轻量级的标记语言。
标记语言旨在将文本内容和结构（比如各级标题、链接、表格、图片、脚注等）结合展现的文本书写方式。
在`Pandoc`的帮助下，markdown语言能够轻松地实现html、pdf或docx文本输出。
这方面你可能听说过一个很强大的排版软件，LaTex。
在很多人看来（包括我），markdown语言很大程度上能够替代LaTex。
他们都能生成pdf（事实上markdown是通过`Pandoc`撰写成tex文件，所以本质上是一回事），而markdown的学习门槛和书写结果都比LaTex友好得多。

本节的核心目的是教会你如何使用rmarkdown进行学术论文写作。
使用进行学术写作的优点有四：

1. 保证分析和文字都在同一个文档中，避免忘记code对应什么内容的情况；
1. 自动生成Replication file, 任何人拿到文件后都能够得出和作者一致的结果，最大程度上实现研究透明；
1. 能轻松导出html，MS word, 或pdf文档，适应中英文写作各种要求。
1. 很好兼容Git版本控制。

## YAML 设置

Rmarkdown写作的第一步应该是设置YAML。
所谓YAML，是“Yet Another Markup Language”的缩写，通常用作全篇样式的设置，写在每篇文章的最开始的位置。
以下是我和我的合作者在*Chinese Journal of International Politics*上发表的“The Resistance and Resilience of National Image Building: An Empirical Analysis of Confucius Institute Closures in the U.S.”一文的YAML设置。^[
Hu, Yue, Yufei Sun, and Donald Lien. 2022. “[The Resistance and Resilience of National Image Building: An Empirical Analysis of Confucius Institute Closures in the U.S.](https://10.1093/cjip/poac010)” *Chinese Journal of International Politics* 15(3): 1–18.
]
我们将逐步介绍其中的设置：

````
---
output: 
  bookdown::pdf_document2:
    fig_caption: true
    number_sections: true

fontsize: 12pt
indent: true
geometry: margin=1in
bibliography: Zotero.bib
csl: chinese-journal-of-international-politics.csl
link-citations: true
colorlinks: true
toc: false

title: 'Resistance and Resilience: A Study of National Image Building Based on Confucius Institute Closures in the U.S.'

author:
- Yue Hu^[Tsinghua University]
- Yufei Sun^[Tsinghua University, Corresponding Author]
- Donald Lien^[University of Texas at San Antonio]

abstract: |
  National image building (NIB) has become a critical strategy in public diplomacy.
  Extending the existing sender-focused literature on NIB, this study takes the receiver side into account.
  Focusing on the closures of a critical NIB effort of China, Confucius Institutes (CIs) in the U.S., we examine how a powerful receiver's resistance affect the image of the sender domestically.
  Based on an extensive dataset of American CIs, we also dig in who exactly in the receiver country promote the resistance.
  The analytic results shows that the CI closures turn down both media tone of and attention to China in the U.S. but locally at most.
  Meanwhile, the empirical evidence also support the resilience of NIB: the remaining CIs still improve local image of China; even in places no CIs left openning, the media attention to China is still higher.
  There are also evidence for the resilience of the NIB efforts: the remaining CIs still improve the media image of China.
  Regarding the promoters of NIB resistance, American colleges show a certain level of autonomy on the CIs' fate; the government has an influence on the issue yet largely through affecting public schools' decisions.
  
  **Keywords:** National image, public diplomacy, Confucius Institutes, U.S-China relations, soft power, GDELT.
---
````

- `output`：用于设置文章的输出类型。
如前所述，`rmarkdown`可以输出html、pdf或docx三种类型，这里是确定输出格式的地方。
    - `bookdown::pdf_document2`：在上面的例子里，我们设置输出格式为pdf，这也是国际期刊投稿的常见格式。
    - `fig_caption: true`：这里表示我们希望文章中显示图片的标题。
    - `number_sections: true`：这里表示我们希望文中标题显示编号。有的期刊可能会有不允许章节编号的要求，此时将`true`变成`false`即可。

:::{.callout-tip}
## Bookdown输出格式

`bookdown`中提供了`pdf_document`和`pdf_document2`两种格式，都可以输出pdf，但后者支持相互参照（cross reference），这个我们之后会讲到。
:::

- 段落格式
    - `fontsize: 12pt`：字体大小，`12pt`是英文发表的标准字体大小
    - `indent: true`：采用每段空两格格式，如果`false`则采用每段顶格，段间空行模式
    - `geometry: margin=1in`：每页边距1 inch
    - `bibliography: Zotero.bib`：为参考文献文件，最方便的是使用Zotero生成，将在 @sec-zotero 详细讲解。
    - `csl: chinese-journal-of-international-politics.csl`：[Citation Style Language (CSL)](https://citationstyles.org/)用于自动设置参考文献格式。换言之，只要你使用rmarkdown就再也不需要手动更改参考文献，只需要找到的对应期刊的`.csl`文件即可。
    - `link-citations: true`：将文中所有引用加入超链接，直接对应最后的参考文献列表的对应位置。
    - `colorlinks: true`：文中超链接采用不同颜色
    - `toc: false`：“table of content"（toc），即目录。通常文章不需要目录，因此我们选择否。

- 首页
    - `title`：文章标题，如果需要副标题，可加`subtitle`选项。
    - `author`：作者
    - `abstract`：摘要和关键字。
  

## 正文设置

````
National image building (NIB) is the efforts of a country to improve the public impressions of and attitudes towards it in a receiver country.
Sender countries commonly expect the NIB efforts to bring better acceptance of their people, products, and investments in the receiver country. 
While NIB has become widely practiced around the world regardless of the country's size or power, there has not been a consensus about its effect. [@Barr2012;@OwenIV2010;@LienEtAl2012;@XiePage2013;@LiEtAl2014;@BrazysDukalskis2019b;@Meng2020]......

# Building National Image: Source, Function, and Effects

......

# Examining NIB Resistance-Resilience Based on CI Closures in the U.S. 

## Data Generation Process

````

一般学术论文正文最多使用三级标题，可如上例使用1~3个#标识。
个数越多，标题层级越低。
`[@xxx]`为生成引文，其生成格式由Zotero内Bibtex生成的Citekey决定，将在 @sec-zotero 部分详细讲解。
此外，除文字外，Rmarkdown还插入代码块、图表等其他内容，可参见[R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/r-code.html)相关内容。


## 中文论文写作

不论是在学校上学还是在国内做研究，Microsoft Word是必用工具。
Rmarkdown可以非常方便地生成docx文档，使你几乎不用再打开Word——以及忍受闪退、格式不统一等Word弊病——实证研究和实证写作的真正融合。

使用Rmakrdown进行Word写作基本步骤和上面完全一样，唯一需要调整的是YAML部分。
以下以我和朱萌在《治理研究》发表的“以语塑心与国民治理：外语习得对政治认知能力的塑造机制研究”的YAML为例进行研究。^[胡悦 and 朱萌. 2022. “以语塑心与国民治理：外语习得对政治认知能力的塑造机制研究.” 《治理研究》38(4): Online.
]
比起之前的例子，最主要的改变是在`output`部分从`bookdown::pdf_document2:`变为`bookdown::word_document2`。
另一个改变重点是`reference_docx: template_cn.docx`。由于中文期刊往往有一些特殊的设置要求包括章节号、段落缩进、字体等等，这些都可以通过`template_cn.docx`以MS Word template方式进行调试。
详细的设置方式可以参考以下两个资源：[R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/word-template.html)和[Authoring Books with R Markdown](https://bookdown.org/yihui/bookdown/internationalization.html)。


````
--
output:
  bookdown::word_document2:
    number_section: false
    reference_docx: template_cn.docx
fontsize: 12 pt
geometry: margin=1in
bibliography:  "language_English.bib"
csl: "american-political-science-review.csl"
link-citations: true
colorlinks: false

title: |
  以语塑心与国民治理：外语习得对政治认知能力的塑造机制研究
author: 
- 胡悦
- 朱萌^[胡悦，清华大学政治学系副教授；朱萌，通讯作者，清华大学政治学系硕士研究生。**基金项目**：国家自然科学基金委青年项目“新型城镇化进程中新老市民身份认同建构的社会心理机制与政策引导路径研究”（72004109），清华大学自主科研项目“新时代国民身份认同建构机制研究”（2019THZWJC47）。]

abstract: |

 **摘要**：
 掌握外语人口增加是现代化发展在个体层面的重要特征，也是一国站稳国际舞台、引领世界潮流的重要前提。
 然而，现有研究多聚焦外语的对外功能和教育手段，对其对内功用，尤其是社会政治功用和治理价值却不甚明了。
 “语言政策场域”理论结合语言治理和语言政治学逻辑填补此方面空白，指出外语习得对国民政治能力（特别是以政治效能感为代表的政治感知能力）的提升效果以及四种作用机制。
 基于全国代表性样本的实证分析支持了该理论的效果和机制假设。
 实证研究表明，中国国民外语（英语）水平对其政治认知能力具有显著促进作用。
 在机制上，外语习得通过信息获取进路上提升内部政治效能感作用最明显，而语言竞争优势则是影响外部效能感的主导路径。
 与此同时，价值西化路径并未对国民政治认知造成明显改变。
 据此，外语习得对于国民政治能力塑造功能更偏向素质性，而非价值性。
 对于语言政策场域理论的系统探讨和实证检验推进了对宏观语言政策微观治理逻辑的理解，为“语言--思维”关系这一经典议题提供新思路和新证据，同时对于像中国这样外语人口日益庞大的现代国家治理也具有重要现实意义，为我国改革语言政策和治理体系、提升国家能力、推动国家治理现代化提供理论借鉴和实证参考。
 
 **关键词**：国家治理能力；政治能力；语言治理；外语习得；政策场域；政治效能感。
 
 Foreign Language and Governance: How Second Language Acquisition Constructs Mass Cognitive Capability for Politics
 
 **Abstract**：The growth of the population comprehending a second language is a characteristic of modernization and the prerequisite of a state's international influence. 
 However, the mainstay of the existing research on second language acquisition (SLA) focuses on international communications and education ignoring SLA's sociopolitical functions and values for domestic governance.
 The novel "language policy field" theory fills this academic vacuum by specifying four paths SLA can affect individuals' political capabilities, especially the cognitive capability. 
 The study based on a nationally representative survey in China supports the hypotheses of this theory. 
 The empirical analyses show that Chinese citizens' English proficiency significantly modifies people's cognitive capability of politics as measured by political efficacy. 
 In terms of the mechanisms, SLA increases the internal efficacy mainly through the information-collection mechanism while raising the external efficacy through the relative-proficiency mechanism. 
 Meanwhile, there is no evidence that SLA affects political capacities through value changes. 
 In this sense, the influence of SLA is more on literacy than on beliefs. 
 The new theory and findings have far-reaching implications on language governance, national capacity, and the modernization of governance in general.
 
 **Keywords**：National capacity of governance; political capacity; language governance; second-language acquisition (SLA); policy field; political efficacy.

---

````
